[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    
python_files = test_*.py
testpaths = 
    tests
    app/test
addopts = -v --cov=app --cov-report=term-missing